# Stage 1: Build the application
FROM node:14 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the application using 'serve' package
FROM node:14 AS production-stage
WORKDIR /app
RUN npm install -g serve
COPY --from=build-stage /app/build ./build

# Serve on port 3000
EXPOSE 3000
CMD ["serve", "-p", "3000", "-s", "build"]
